### ISSUE TITLE
makes BorderRadius as BorderRadiuconst s

### ISSUE THREAD

**Issue by Nag112** [carlosfiori/dart-auto-const#1]

**Comment by carlosfiori** [comment]
Hi @Nag112 could you please describe better what do you want?

**Comment by Nag112** [comment]
borderRadius:
                                      const BorderRadiuconst s.all(Radius.circular(4)),

**Comment by Nag112** [comment]
const Color(0xff3BEBconst 9E) : Color(0xff007FE4),
