### ISSUE TITLE
makes child a some places as const hild

### ISSUE THREAD

**Issue by Nag112** [carlosfiori/dart-auto-const#2]

**Comment by carlosfiori** [comment]
Hi @Nag112 could you please describe better what do you want?

**Comment by Nag112** [comment]
const Tab(cconst hild: Padding(
                          padding: EdgeInsets.symmetric(horizontal: 18),
                          child: Text("Rewards", style: TextStyle(
                              fontSize: 14,
                              fontFamily: 'JosefinSans',
                              color: Colors.white,
                              fontWeight: FontWeight.w300),),
                        ),),
                        const Tab(cconst hild: Padding(
                          padding: EdgeInsets.symmetric(horizontal: 18),
                          child: Text("Redeems", style: TextStyle(
                              fontSize: 14,
                              fontFamily: 'JosefinSans',
                              color: Colors.white,
                              fontWeight: FontWeight.w300),),
                        ),),
